#!/usr/bin/env bash
# scripts/gen_assets.sh — encode nuclei-templates/ and rules/ into Go source.
# Run from project root: bash scripts/gen_assets.sh
set -euo pipefail

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
OUT="$ROOT/internal/assets/assets_gen.go"

cat > "$OUT" << 'HEADER'
//go:build gen_assets

// Code generated by scripts/gen_assets.sh; DO NOT EDIT.
package assets

import (
	"encoding/base64"
	"io/fs"
	"path"
	"strings"
	"time"
)

type file struct {
	Path string
	Data string // base64 encoded
}

var embeddedFiles []file

func init() {
	embeddedFiles = []file{
HEADER

# Encode each file — use relative paths
encode_dir() {
    local dir="$1"
    # Run find from project root to get relative paths like nuclei-templates/foo.yaml
    local files
    files=$(cd "$ROOT" && find "$dir" -type f | sort)
    local olddir
    olddir=$(pwd)
    cd "$ROOT"
    while IFS= read -r relpath; do
        relpath="${relpath//\\//}"
        b64=$(base64 -w0 < "$relpath")
        printf '\t\t{Path: "%s", Data: "%s"},\n' "$relpath" "$b64" >> "$OUT"
    done <<< "$files"
    cd "$olddir"
}

encode_dir "nuclei-templates"
encode_dir "rules"

cat >> "$OUT" << 'FOOTER'
	}
}

// List returns all embedded file paths.
func List() []string {
	paths := make([]string, len(embeddedFiles))
	for i, f := range embeddedFiles {
		paths[i] = f.Path
	}
	return paths
}

// ReadFile returns the content of an embedded file.
func ReadFile(name string) ([]byte, error) {
	for _, f := range embeddedFiles {
		if f.Path == name {
			return base64.StdEncoding.DecodeString(f.Data)
		}
	}
	return nil, &fs.PathError{Op: "read", Path: name, Err: fs.ErrNotExist}
}

// ListDir returns entries under a directory prefix.
func ListDir(dir string) []string {
	prefix := dir
	if !strings.HasSuffix(prefix, "/") {
		prefix += "/"
	}
	seen := make(map[string]bool)
	var result []string
	for _, f := range embeddedFiles {
		if !strings.HasPrefix(f.Path, prefix) {
			continue
		}
		rest := f.Path[len(prefix):]
		// Direct child only
		if idx := strings.Index(rest, "/"); idx >= 0 {
			sub := rest[:idx]
			if !seen[sub] {
				seen[sub] = true
				result = append(result, sub+"/")
			}
		} else {
			result = append(result, rest)
		}
	}
	return result
}

// memFS implements fs.FS over embedded files.
type memFS struct{ root string }

// FS returns an fs.FS rooted at the given directory.
func FS(root string) fs.FS { return &memFS{root: root} }

func (m *memFS) Open(name string) (fs.File, error) {
	full := path.Join(m.root, name)
	for _, f := range embeddedFiles {
		if f.Path == full {
			data, err := base64.StdEncoding.DecodeString(f.Data)
			if err != nil {
				return nil, err
			}
			return &memFile{name: path.Base(full), data: data}, nil
		}
	}
	return nil, &fs.PathError{Op: "open", Path: name, Err: fs.ErrNotExist}
}

type memFile struct {
	name string
	data []byte
	off  int
}

func (f *memFile) Stat() (fs.FileInfo, error) { return f, nil }
func (f *memFile) Read(b []byte) (int, error) {
	if f.off >= len(f.data) {
		return 0, fs.ErrClosed
	}
	n := copy(b, f.data[f.off:])
	f.off += n
	return n, nil
}
func (f *memFile) Close() error               { return nil }
func (f *memFile) Name() string               { return f.name }
func (f *memFile) Size() int64                { return int64(len(f.data)) }
func (f *memFile) Mode() fs.FileMode          { return 0444 }
func (f *memFile) ModTime() time.Time         { return time.Time{} }
func (f *memFile) IsDir() bool                { return false }
func (f *memFile) Sys() interface{}           { return nil }
FOOTER

# Count files
total=$(grep -c 'Path:' "$OUT" || true)
echo "[+] Generated $OUT with $total embedded files"
